package com.GreenThumb.GT.models.KnowledgeResource;
public enum ResourceCategory {
    GARDENING_BASICS,
    PLANT_CARE,
    SUSTAINABLE_LIVING,
    URBAN_FARMING,
    ORGANIC_GARDENING,
    HYDROPONICS,
    PERMACULTURE,
    LANDSCAPING,
    PEST_CONTROL,
    HERBALISM,
    COMPOSTING,
    BOTANY,
    SEASONAL_GARDENING,
    GARDEN_TOOLS,
    DIY_PROJECTS,
    WILDLIFE_GARDENING,
    WATER_CONSERVATION,
    COMMUNITY_GARDENING
}
